# Generated by Django 5.2.7 on 2025-11-23 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0004_alter_food_description_alter_food_name_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='photo',
        ),
        migrations.AddField(
            model_name='food',
            name='sale',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(to='Foods.food')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
