# Generated by Django 5.2.7 on 2025-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0005_remove_food_photo_food_sale_favoritefood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='sale',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
