# Generated by Django 5.2.7 on 2025-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0006_alter_food_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='sale',
            field=models.IntegerField(db_column='Скидка', max_length=100, null=True),
        ),
    ]
